# Config file for Air in TOML format

# Working directory
root = "."
tmp_dir = "tmp"

[build]
before = ["make build-deps", "make bindata-dev"]
cmd = "go build -o ./${tmp_dir}/main ./cmd/dkf/main.go"
bin = "./${tmp_dir}/main"
include_ext = ["go", "css", "html", "gohtml", "md"]
exclude_dir = [
  "assets", "tmp", "vendor", "scripts", "dist", "bindata",
  "coverage", "scss", "bootstrap", ".git", "node_modules", "cmd", "_locales", "samples"
]
log = "air.log"
delay = 500 # ms
stop_on_error = true
send_interrupt = false
kill_delay = 0 # ms

[log]
time = true

[color]
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

[misc]
clean_on_exit = true

# Add custom build steps for dependencies
[build.pre_build]
command = "make get-deps"

# Add custom build steps for building the binary with extra tags
[build.post_build]
command = "mv main ${tmp_dir}/"

# Add custom build steps for cleaning up after build errors
[build.clean_up]
command = "rm -f ${tmp_dir}/main"
