-- +migrate Up
CREATE TABLE IF NOT EXISTS spam_filters (
    id INTEGER NOT NULL PRIMARY KEY,
    filter VARCHAR(255) NOT NULL,
    is_regex TINYINT(1) NOT NULL DEFAULT 0,
    action INTEGER NOT NULL DEFAULT 0,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP);

-- +migrate Down
